version: "3"

services:
  mysql8:
    image: mysql:8.0.23
    volumes:
      - ./docker/mysql8/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gravityr
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  postgres14:
    image: postgres:14
    volumes:
      - ./docker/postgres14/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gravityr
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  aws_mock:
    build:
      context: ./docker/aws_mock
    volumes:
      - ./docker/aws_mock/fastapi:/app
    ports:
      - "8080:8080"
