version: "3"

services:
  bff:
    build: ./bff
    volumes:
      - ./bff:/app
    ports:
      - "9001:9001"
  user:
    build: ./user
    volumes:
      - ./user:/app
    ports:
      - "9002:9002"
    restart: unless-stopped
  user_db_mysql:
    image: mysql:8.0.23
    volumes:
      - ./docker/user_db_mysql/data:/var/lib/mysql
      - ./docker/user_db_mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "9006:3306"
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  jaeger:
    image: jaegertracing/all-in-one:1.38
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
      - "16685:16685"
      - "16686:16686"
      - "16687:16687"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      COLLECTOR_OTLP_ENABLED: true
