table:
  name: users
  schema: public
array_relationships:
  - name: tasks
    using:
      manual_configuration:
        column_mapping:
          id: user_id
        insertion_order: null
        remote_table:
          name: tasks
          schema: public
